# Generated by Django 3.2.7 on 2023-01-05 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('specialization', models.CharField(max_length=255)),
                ('hospital', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'disease',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('service_id', models.IntegerField()),
                ('services', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'search',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Diseases',
        ),
    ]
