# Generated by Django 4.1.3 on 2023-01-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0003_delete_disease_delete_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('fullname', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('contact_number', models.CharField(max_length=255)),
                ('blood_type', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('allergies', models.CharField(max_length=255)),
            ],
        ),
    ]
